### ISSUE TITLE
Offset error 

### ISSUE THREAD

**Issue by barrett092** [Kevin-Robertson/InveighZero#1]
Not sure if this error is even serious as the program still runs but I get this here and there while it's running:

[-] [2020-06-29T11:31:25] Packet sniffing error detected - System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at Inveigh.Util.ParseNameQuery(Int32 index, Byte[] nameQuery) in C:\Users\pentester\Downloads\InveighZero-master\InveighZero-master\Inveigh\Util.cs:line 543
   at Inveigh.Sniffer.SnifferSpoofer(String ipVersion, String snifferIP, String snifferMAC, String spooferIP, String spooferIPv6, String dnsDomainController, String dnsTTL, String llmnrTTL, String mdnsTTL, String nbnsTTL, String[] dnsTypes, String[] mdnsQuestions, String[] mdnsTypes, String[] nbnsTypes, String dhcpv6DomainSuffix, String[] pcapTCP, String[] pcapUDP) in C:\Users\pentester\Downloads\InveighZero-master\InveighZero-master\Inveigh\Sniffer.cs:line 445

**Comment by qgrosperrin** [comment]
I have the same. Unexplained for me so far
